run:
  modules-download-mode: readonly

linters:
  disable:
    - depguard
    - exhaustruct
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
