// Code generated by mockery v2.23.1. DO NOT EDIT.

package s2x

import mock "github.com/stretchr/testify/mock"

// MockRows is an autogenerated mock type for the Rows type
type MockRows struct {
	mock.Mock
}

type MockRows_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRows) EXPECT() *MockRows_Expecter {
	return &MockRows_Expecter{mock: &_m.Mock}
}

// Columns provides a mock function with given fields:
func (_m *MockRows) Columns() ([]string, error) {
	ret := _m.Called()

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRows_Columns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Columns'
type MockRows_Columns_Call struct {
	*mock.Call
}

// Columns is a helper method to define mock.On call
func (_e *MockRows_Expecter) Columns() *MockRows_Columns_Call {
	return &MockRows_Columns_Call{Call: _e.mock.On("Columns")}
}

func (_c *MockRows_Columns_Call) Run(run func()) *MockRows_Columns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRows_Columns_Call) Return(_a0 []string, _a1 error) *MockRows_Columns_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRows_Columns_Call) RunAndReturn(run func() ([]string, error)) *MockRows_Columns_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function with given fields: dest
func (_m *MockRows) Scan(dest ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, dest...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(...interface{}) error); ok {
		r0 = rf(dest...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRows_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockRows_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - dest ...interface{}
func (_e *MockRows_Expecter) Scan(dest ...interface{}) *MockRows_Scan_Call {
	return &MockRows_Scan_Call{Call: _e.mock.On("Scan",
		append([]interface{}{}, dest...)...)}
}

func (_c *MockRows_Scan_Call) Run(run func(dest ...interface{})) *MockRows_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockRows_Scan_Call) Return(_a0 error) *MockRows_Scan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRows_Scan_Call) RunAndReturn(run func(...interface{}) error) *MockRows_Scan_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockRows interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockRows creates a new instance of MockRows. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRows(t mockConstructorTestingTNewMockRows) *MockRows {
	mock := &MockRows{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
